-- Add db tables, schemas, sequences here
-- Make this as close to the Db2datbase def as possible

--example
-- DROP SCHEMA IF EXISTS MY_SCHEMA;
-- CREATE SCHEMA IF NOT EXISTS MY_SCHEMA AUTHORIZATION SA;

-- DROP TABLE IF EXISTS MY_SCHEMA.MY_TABLE;
-- CREATE TABLE MY_SCHEMA.MY_TABLE ( ...
-- );

-- CREATE SEQUENCE MY_SCHEMA.MY_SEQ START WITH 1 INCREMENT BY 1;

-- Dummy stuff, remove

CREATE SCHEMA IF NOT EXISTS DUMMYSC AUTHORIZATION SA;

DROP TABLE IF EXISTS DUMMYSC.DUMMY_TABLE;
create table DUMMYSC.DUMMY_TABLE (
	ID BIGINT NOT NULL,
	VALUE VARCHAR(50),
	CONSTRAINT ID_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE DUMMYSC.DUMMY_SEQ START WITH 1000 INCREMENT BY 1;